Cuda available? False
creating dir ./training_logs/Adult/ARL/seed_run_version_0/seed_8
GPU available: False, used: False
TPU available: None, using: 0 TPU cores

  | Name      | Type              | Params
------------------------------------------------
0 | learner   | Learner           | 8.6 K 
1 | adversary | Adversary         | 103   
2 | loss_fct  | BCEWithLogitsLoss | 0     
------------------------------------------------
8.7 K     Trainable params
0         Non-trainable params
8.7 K     Total params
/home/nolte/.conda/envs/fact-ai-lisa/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: training_step returned None if it was on purpose, ignore this warning...
  warnings.warn(*args, **kwargs)
time to fit was 49.02394652366638
Results = {'min_auc': 0.8818347454071045, 'macro_avg_auc': 0.9167790114879608, 'micro_avg_auc': 0.9073155522346497, 'minority_auc': 0.9416649341583252, 'accuracy': 0.8471224308013916}
